name: mist
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.0
  google_fonts: ^6.2.1

  shared_preferences: ^2.3.2
  flutter_mobx: ^2.2.1+1
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.2
  image: ^4.3.0
  fluttertoast: ^8.2.8
  intl: ^0.20.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  country_code_picker: ^3.1.0
#  telephony: ^0.2.0
  dropdown_search: ^6.0.1
#  permission_handler: ^11.3.1
#  emoji_regex: ^0.0.5
  dotted_border: ^2.1.0
  lottie: ^3.3.1


  #Firebase
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_auth: ^5.3.1
  firebase_analytics: ^11.4.0

  #new
  carousel_slider: ^5.0.0
  story_view: ^0.16.5
  custom_rating_bar: ^3.0.0
  linear_progress_bar: ^1.1.3
  razorpay_flutter: ^1.4.0
  toastification: ^3.0.2


  #location
  permission_handler: ^11.4.0
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.0
  geocoding: ^3.0.0

  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0
  table_calendar: ^3.2.0
  flutter_time_picker_spinner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/vehicle_logo/
    - assets/vehicle_images/
    - assets/vehicle_images/audi/
    - assets/lottiefile/

